blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/', PostListView.as_view(), name='post_list'),
    #path('post/<slug:slug>/', PostDetailView.as_view(), name='detail'), 이러면 한글을 처리 못함
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post_detail'),
]
urlpatterns += [
    path('archive/', PostArchiveView.as_view(),name='post_archive'),
    path('archive/<int:year>/', PostYearArchiveView.as_view(),name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDayArchiveView.as_view(),name='post_day_archive'),
    path('archive/today/', PostTodayArchiveView.as_view(), name='post_today_archive'),
]
urlpatterns += [
    path('tag/', TagCloudTemplateView.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectListView.as_view(), name='tagged_object_list'),
]

urlpatterns += [
    path('search/', SearchFormView.as_view(), name='search'),
]
# CRUD
urlpatterns += [
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeListView.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.views import *
from django.conf.urls.static import static
from django.conf import settings

# from bookmark.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
]

#bookmark
# urlpatterns += [
#     path('bookmark/', BookmarkLV.as_view(), name='index'),
#     path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
# ]
urlpatterns += [
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += [
    path('', HomeView.as_view(), name='home')
]

urlpatterns += [
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#login
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreatedDoneTemplateView.as_view(), name='register_done'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(verbose_name='TITLE', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    image = models.ImageField('IMAGE', upload_to='SorlPhoto/%Y', null=True)
    created_date = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_date = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog.posts'
        ordering = ('-modify_date',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_date()
    
    def get_next(self):
        return self.get_next_by_modify_date()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args,**kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")

blog/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import *
from django.conf import settings
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from myblog.views import OwnerOnlyMixin

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5

class PostDetailView(DetailView):
    model = Post
    #disqus 댓글기능
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url}"
        context['disqus_title'] = f'{self.object.slug}'
        return context



# Post를 쓴 적이 없으면 안됨
class PostArchiveView(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive.html'

class PostYearArchiveView(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_year.html'
    make_object_list = True

class PostMonthArchiveView(MonthArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_month.html'

class PostDayArchiveView(DayArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_day.html'

class PostTodayArchiveView(TodayArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_day.html'



#taggit
class TagCloudTemplateView(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectListView(ListView):
    model = Post
    template_name = 'taggit/taggit_post_list.html'

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context



class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()

        context = dict()
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)



#CRUD
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'tags']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse('blog:detail',kwargs={'pk': self.object.id })

class PostChangeListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/post_change_list.html'    

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user).order_by('id')

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'tags']
    success_url = reverse_lazy('blog:index')

    def get_success_url(self):
        return reverse('blog:detail',kwargs={'pk': self.object.id })

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% block title %}
post_all.html
{% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Blog List</h1>
<br>

{% for post in posts %}

    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>

{% endfor %}

<br>

<div>
    <span>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
</div>
{% endblock %}

blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

{% block title %}post_change_list.html{% endblock %}

{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}

{% block content %}

<h1>My Post - {{ user }}</h1>
<br>

<table class="table">
    <caption>{{ user }}'s posts</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Owner</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for post in object_list %}
      <tr>
        <th scope="row">{{ post.id }}</th>
        <td>{{ post.title }}</td>
        <td>{{ post.description }}</td>
        <td>{{ post.owner }}</td>
        <td class="table-info"><a href="{% url 'blog:update' post.id %}">update</a></td>
        <td class="table-danger"><a href="{% url 'blog:delete' post.id %}">delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}post_confirm_delete.html{% endblock %}

{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}

{% block content %}

    <h1>Are you sure?</h1>
    <br>

    <form action="." method="POST">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
    </form>
    
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}
post_detail.html
{% endblock %}

{% block extra-style %}
<style>
    .post-body {
        width: 80%;
        margin: auto;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
        font-size: 16px;
    }
</style>
{% endblock %}

{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}

{% block content %}
<div class="post-body">
    <h2>{{ object.title }}</h2>

    <p>
        {% if object.get_previous %}
            <a href="{{ object.get_previous.get_absolute_url }}", title="View previous post">
                &laquo;-- {{ object.get_previous }}
            </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}", title="View next post">{{ object.get_next }} --&raquo; </a>
        {% endif %}
    </p>

    <p>
        {{ object.modify_date|date:"j F Y" }}
    </p>
    <br>
    
    <div class="body">
        <a href="{{ object.image.url }}">
            <img src="{{ object.image.url }}" class="img-fluid">
        </a>
        {{ object.content|linebreaks }}
    </div>

    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %} 
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}
        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{ tag.name }}</a>
        {% endfor %}
        &emsp;
        <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span> </a>
    </div>
    <div id="disqus_thread"></div>

</div>
{% endblock %}

{% block extra-script %}
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    
    var disqus_config = function () {
    this.page.url = '{{ disqus_url }}';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '{{ disqus_id }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    this.page.title = '{{ disqus.title }}'
    };
    
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}

{% block content %}

    <h1>Post Create/Update By {{ user }}</h1>
    
    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Attention!</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.content|add_class:"form-control"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.tags|add_class:"form-control"}}
            </div>
        </div>
        <br>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-outline-success"/>
            </div>
        </div>
    </form>

{% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}
{% block title %}post_search.html{% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Blog search</h1>
<br>

<form action="." method="post"> {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>
<br><br>

{% if object_list %}
{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {{ post.modify_date|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}
{% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}