blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/', PostListView.as_view(), name='post_list'),
    #path('post/<slug:slug>/', PostDetailView.as_view(), name='detail'), 이러면 한글을 처리 못함
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post_detail'),
]
urlpatterns += [
    path('archive/', PostArchiveView.as_view(),name='post_archive'),
    path('archive/<int:year>/', PostYearArchiveView.as_view(),name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDayArchiveView.as_view(),name='post_day_archive'),
    path('archive/today/', PostTodayArchiveView.as_view(), name='post_today_archive'),
]
urlpatterns += [
    path('tag/', TagCloudTemplateView.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectListView.as_view(), name='tagged_object_list'),
]

urlpatterns += [
    path('search/', SearchFormView.as_view(), name='search'),
]
# CRUD
urlpatterns += [
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeListView.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.views import *
from django.conf.urls.static import static
from django.conf import settings

# from bookmark.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
]

#bookmark
# urlpatterns += [
#     path('bookmark/', BookmarkLV.as_view(), name='index'),
#     path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
# ]
urlpatterns += [
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += [
    path('', HomeView.as_view(), name='home')
]

urlpatterns += [
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#login
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreatedDoneTemplateView.as_view(), name='register_done'),
]

photo/urls.py
from django.urls import path
from photo.views import *

app_name = 'photo'
urlpatterns = [
    path('', AlbumListView.as_view(), name='index'),
    path('album', AlbumListView.as_view(), name='album_list'),
    path('album/<int:pk>', AlbumDetailView.as_view(), name='album_detail'),
    path('photo/<int:pk>', PhotoDetailView.as_view(), name='photo_detail'),
]

urlpatterns += [
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeListView.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
]

urlpatterns += [
    path('album/add/', AlbumPhotoCreateView.as_view(), name='album_add'),
    path('album/change/', AlbumChangeListView.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUpdateView.as_view(),name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
]

photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# from photo.fields import ThumbnailImageField

# Create your models here.
class Album(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', arg=(self.id,))

class Photo(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo description', blank=True)
    # image = ThumbnailImageField(upload_to='photo/%Y/%m')
    image = models.ImageField('IMAGE', upload_to='SorlPhoto/%Y')
    upload_date = models.DateTimeField('Upload date', auto_now_add=True)

    class Meta:
        ordering = ('title',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic import *
from photo.models import *
from photo.form import PhotoInlineFormSet
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from myblog.views import OwnerOnlyMixin
# Create your views here.


class AlbumListView(ListView):
    model = Album

class AlbumDetailView(DetailView):
    model = Album

class PhotoDetailView(DetailView):
    model = Photo



class PhotoCreateView(CreateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PhotoChangeListView(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user).order_by('id')

class PhotoUpdateView(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

class AlbumChangeListView(LoginRequiredMixin, ListView):
    model = Album
    template_name= 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user).order_by('id')

class AlbumDeleteView(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')

class AlbumPhotoCreateView(LoginRequiredMixin, CreateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset']= PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_vaild():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUpdateView(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset']= PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_vaild():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

{% block title %}album_change_list.html{% endblock %}

{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}

{% block content %}

<h1>My Album - {{ user }}</h1>
<br>

<table class="table">
    <caption>{{ user }}'s albums</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Owner</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for album in object_list %}
      <tr>
        <th scope="row">{{ album.id }}</th>
        <td>{{ album.name }}</td>
        <td>{{ album.description }}</td>
        <td>{{ album.owner }}</td>
        <td class="table-info"><a href="{% url 'photo:album_update' album.id %}">update</a></td>
        <td class="table-danger"><a href="{% url 'photo:album_delete' album.id %}">delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

{% endblock %}

photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}album_confirm_delete.html{% endblock %}

{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}

{% block content %}

    <h1>Are you sure?</h1>
    <br>

    <form action="." method="POST">{% csrf_token %}
        <p>Are you sure you want to delete <strong>"{{ object }}"</strong></p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
    </form>
    
{% endblock %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}
{% load sorl_thumbnail %}
{% block title %}album_detial.html{% endblock %}
{% block extra-style %}
<style>
    thumbnail{
        border: 5px solid #ccc;
    }
</style>
{% endblock %}
{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}
{% block content %}


    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span>
        <span class="h5 font-italic">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class='row'>
        {% for photo in object.photo_set.all %}
        <div class="col-md-3 mb-5">
            <div class="thumbnail">
                <a href="{{ photo.get_absolute_url }}">
                    {% thumbnail photo.image "512x512" crop="center" as im %}
                    <img src="{{ im.url }}" style="width: 100%;">
                    {% endthumbnail %}
                </a>
            </div>
            <ul>
                <li class="font-italic">{{ photo.title }}</li>
                <li class="font-italic">{{ photo.upload_date|date:"Y-m-d" }}</li>
            </ul>
        </div>
        {% empty %}
        <b><i>Empty</i></b>
        {% endfor %}
    </div>


{% endblock %}

photo/templates/photo/album_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}album_form.html{% endblock %}
{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}
{% block content %}
    <h1>Album-Photo Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Attention!</div>
        {{ form.errors }}
    </div>
    {% endif %}

    {% if formset.errors %}
    <div class="alert alert-warning">
        <div class="font-weight-bold">Attention!</div>
        {% for formerrors in formset.errors %}
            {{ formerrors }}
        {% endfor %}
    </div>
    {% endif %}

    {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
    {% endif %}
    {% csrf_token %}

        <h4>create or update album contents</h4>

        <fieldset class="card pt-3">

            <div class="form-group row">
                {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.description|add_class:"form-control" }}
                </div>
            </div>

        </fieldset>
        <br>

        <h4>create or update photo contents</h4>

        <fieldset class="card pt-3">

            {{ formset.management_form }}
            {% for form in formset %}
                {{ form.id }}
                {# form.album #}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <hr>
            {% endfor %}

        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-outline-success"/>
            </div>
        </div>

    </form>

{% endblock %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}
{% load sorl_thumbnail %}
{% block title %}album_list.html{% endblock %}
{% block extra-style %}
<style>
    thumbnail{
        border: 3px solid #ccc;
    }
</style>
{% endblock %}
{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}
{% block content %}

    {% for album in object_list %}

    <div class="mt-5">
        <a class="h2" href="{% url 'photo:album_detail' album.id %}">
            {{ album.name }}
        </a>&emsp;
        <span class='font-italic h5'>{{ album.description }}</span>
    </div>

    <hr style="margin:  0 0 20px 0;">

    <div class='row'>
        {% for photo in album.photo_set.all|slice:":4" %}
        <div class="col-3 mb-5">
            <div class="ml-5">
                <a href="{{ photo.get_absolute_url }}">
                    {% thumbnail photo.image "512x512" crop="center" as im %}
                    <img src="{{ im.url }}" style="width: 100%;">
                    {% endthumbnail %}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>    
    {% empty %}
    <b><i>Empty</i></b>
    {% endfor %}
    

{% endblock %}

photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

{% block title %}photo_change_list.html{% endblock %}

{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}

{% block content %}

<h1>My photo - {{ user }}</h1>
<br>

<table class="table">
    <caption>{{ user }}'s photos</caption>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Owner</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for photo in object_list %}
      <tr>
        <th scope="row">{{ photo.id }}</th>
        <td><a href="{% url 'photo:photo_detail' photo.id %}">{{ photo.title }}</a></td>
        <td>{{ photo.description }}</td>
        <td>{{ photo.owner }}</td>
        <td class="table-info"><a href="{% url 'photo:photo_update' photo.id %}">update</a></td>
        <td class="table-danger"><a href="{% url 'photo:photo_delete' photo.id %}">delete</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endblock %}

photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}

{% block content %}

    <h1>Are you sure?</h1>
    <br>

    <form action="." method="POST">{% csrf_token %}
        <p>Are you sure you want to delete <strong>"{{ object }}"</strong></p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
    </form>
    
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}photo_detail.html{% endblock %}

{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}

{% block content %}

    <h2 class="mt-5">{{ object.title }}</h2>
    
    <hr style="margin:  0 0 20px 0;">

    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%;">
            </a>
        </div>
    

    <ul class="col-md-3 mt-3">
        <li class="h5">Photo Description</li>
            {% if object.description %}<p>{{ object.description|linebreaks }}</p>
            {% else %}<p>(blank)</p>{% endif %}
        <li class="h5">Date Uploaded</li>
            <p class="font-italic">{{ object.upload_date }}</p>
        <li class="h5">Album Name</li>
            <p class="font-italic">
            <a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a>
            </p>
    </ul>
    </div>
{% endblock %}

photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}photo_form.html{% endblock %}
{% block apadd %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Add
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a></li>
        <li><a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a></li>
      </ul>
</li>
{% endblock %}
{% block content %}

    <h1>Photo Create/Update By {{ user }}</h1>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Attention!</div>
        {{ form.errors }}
    </div>
    {% endif %}
    
    {% if form.is_multipart %}
    <form enctype="multipart/form-data" action="" method="post" class="card pt-3">
    {% else %}
    <form action="." method="POST" class="card pt-3">
    {% endif %}{% csrf_token %}
        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold"}}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control"}}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">Add Album</a>
            </div>
            
        </div>
        <br>
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file"}}
            </div>
        </div>
        <br>
        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>
        <br>
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-outline-success"/>
            </div>
        </div>


    </form>
{% endblock %}