blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/', PostListView.as_view(), name='post_list'),
    #path('post/<slug:slug>/', PostDetailView.as_view(), name='detail'), 이러면 한글을 처리 못함
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post_detail'),
]
urlpatterns += [
    path('archive/', PostArchiveView.as_view(),name='post_archive'),
    path('archive/<int:year>/', PostYearArchiveView.as_view(),name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDayArchiveView.as_view(),name='post_day_archive'),
    path('archive/today/', PostTodayArchiveView.as_view(), name='post_today_archive'),
]
urlpatterns += [
    path('tag/', TagCloudTemplateView.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectListView.as_view(), name='tagged_object_list'),
]

urlpatterns += [
    path('search/', SearchFormView.as_view(), name='search'),
]
# CRUD
urlpatterns += [
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeListView.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

bookmark/urls.py
from django.contrib import admin
from django.urls import path, include

from bookmark.views import *

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>', BookmarkDV.as_view(), name='detail'),
]

urlpatterns += [
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('<int:pk>/update/', BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name='delete'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.views import *
from django.conf.urls.static import static
from django.conf import settings

# from bookmark.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
]

#bookmark
# urlpatterns += [
#     path('bookmark/', BookmarkLV.as_view(), name='index'),
#     path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
# ]
urlpatterns += [
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += [
    path('', HomeView.as_view(), name='home')
]

urlpatterns += [
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#login
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreatedDoneTemplateView.as_view(), name='register_done'),
]

photo/urls.py
from django.urls import path
from photo.views import *

app_name = 'photo'
urlpatterns = [
    path('', AlbumListView.as_view(), name='index'),
    path('album', AlbumListView.as_view(), name='album_list'),
    path('album/<int:pk>', AlbumDetailView.as_view(), name='album_detail'),
    path('photo/<int:pk>', PhotoDetailView.as_view(), name='photo_detail'),
]

urlpatterns += [
    path('photo/add/', PhotoCreateView.as_view(), name='photo_add'),
    path('photo/change/', PhotoChangeListView.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(),name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
]

urlpatterns += [
    path('album/add/', AlbumPhotoCreateView.as_view(), name='album_add'),
    path('album/change/', AlbumChangeListView.as_view(), name='album_change'),
    path('album/<int:pk>/update/', AlbumPhotoUpdateView.as_view(),name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}Django Web Programming{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        
        {% block extra-style %}{% endblock %}
        <!-- 왜 작동을 안하지-->
        <style> 
          .font-weight-bold{
            font-weight: bold;
          }
        </style>
    </head>

    <body style="padding-top: 90px;">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand mx-3 mb-0 font-weight-bold font-italic" href="{% url 'home' %}">Django - Python Web Programming</a>
              
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'bookmark:index' %}">Bookmark</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'photo:index' %}">Photo</a>
                  </li>

                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Util
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a></li>
                      <li><a class="dropdown-item" href="{% url 'blog:search' %}">Search</a></li>
                    </ul>

                  </li>
                  {% block apadd %}
                  <li class="nav-item">
                    {% block add %}
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Add</a>
                    {% endblock add %}
                  </li>
                  {% endblock apadd %}
                </ul>
                  <form class="d-flex" action="" method="post"> {% csrf_token %}
                   <input class="form-control me-2" type="search" placeholder="Search" name='search_word'>
                   <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                  
                  <div class="navbar-nav">
                  <li class="nav-item dropdown mx-1">
                    {% if user.is_active %}
                    <a class="nav-link dropdown-toggle" href="" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                      <li><a class="dropdown-item" href="{% url 'blog:change' %}">My Post</a></li>
                      <li><a class="dropdown-item" href="{% url 'photo:album_change' %}">My Album</a></li>
                      <li><a class="dropdown-item" href="{% url 'photo:photo_change' %}">My Photo</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                      <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                    </ul>
                    {% else %}
                    <a class="nav-link dropdown-toggle" href="" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="far fa-user"></i>&ensp;Anonymous&ensp;
                    </a>

                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                      <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                      <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                    </ul>
                    {% endif %}
                  </li>
                  </div>


                

              </div>
            </div>
          </nav>
        
          
          <div class="container">
            
            {% block content %}{% endblock %}
              
          </div>
          
          {% block footer %}{% endblock %}

        


          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
          <script src="https://kit.fontawesome.com/cc0f26cd3f.js" crossorigin="anonymous"></script>
          {% block extra-script %}{% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
home.html
{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
  background-image: url("{% static 'img/lion.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: 100%;
  height: 500px;
  border-top: 10px solid #ccc;
  border-bottom: 10px solid #ccc;
  padding: 20px 0 0 20px;
} 

.title {
  color: cornflowerblue;
  font-weight: bold;
  text-shadow: -2px 0 #000, 0 2px #000, 2px 0 #000, 0 -2px #000;;
}

.powered {
  position: relative;
  top: 77%;
  color: #cc0;
  font-style: italic;
}
</style>
{% endblock %}


{% block content %}
  <div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
  </div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6">
      <h3>Bookmark App</h3>
      <p>Bookmark is a Uniform Resource Identifier (URL)
        that  is stored for later retrieval in any of various storage format.
        You can store your own bookmarks by Bookmark application.
        It's also possible to update or delete your bookmarks.
      </p>
    </div>
    <div class="col-sm-6">
      <h3>Blog App</h3>
      <p>This application makes it possible to log daily events or write your own interests
        such as hobbies, techniques, etc.
        A typical blog combines text, digital images, and links to other blogs, web pages,
        and other media related to its topic.
      </p>
    </div>
  </div>
{% endblock %}


{% block footer %}
<footer class="fixed-bottom mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</span>
    </div>
  </footer>
{% endblock %}