blog/urls.py
from django.urls import path, re_path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/', PostListView.as_view(), name='post_list'),
    #path('post/<slug:slug>/', PostDetailView.as_view(), name='detail'), 이러면 한글을 처리 못함
    re_path(r'^post/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post_detail'),
]
urlpatterns += [
    path('archive/', PostArchiveView.as_view(),name='post_archive'),
    path('archive/<int:year>/', PostYearArchiveView.as_view(),name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', PostDayArchiveView.as_view(),name='post_day_archive'),
    path('archive/today/', PostTodayArchiveView.as_view(), name='post_today_archive'),
]
urlpatterns += [
    path('tag/', TagCloudTemplateView.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', TaggedObjectListView.as_view(), name='tagged_object_list'),
]

urlpatterns += [
    path('search/', SearchFormView.as_view(), name='search'),
]
# CRUD
urlpatterns += [
    path('add/', PostCreateView.as_view(), name='add'),
    path('change/', PostChangeListView.as_view(), name='change'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from myblog.views import *
from django.conf.urls.static import static
from django.conf import settings

# from bookmark.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
]

#bookmark
# urlpatterns += [
#     path('bookmark/', BookmarkLV.as_view(), name='index'),
#     path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),
# ]
urlpatterns += [
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += [
    path('', HomeView.as_view(), name='home')
]

urlpatterns += [
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#login
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreatedDoneTemplateView.as_view(), name='register_done'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify

class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(verbose_name='TITLE', max_length=100)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    image = models.ImageField('IMAGE', upload_to='SorlPhoto/%Y', null=True)
    created_date = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_date = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog.posts'
        ordering = ('-modify_date',)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_date()
    
    def get_next(self):
        return self.get_next_by_modify_date()
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args,**kwargs)

blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label="Search Word")

blog/views.py
from django.shortcuts import render
from django.views.generic import *
from .models import *
from django.conf import settings
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from myblog.views import OwnerOnlyMixin

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5

class PostDetailView(DetailView):
    model = Post
    #disqus 댓글기능
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url}"
        context['disqus_title'] = f'{self.object.slug}'
        return context



# Post를 쓴 적이 없으면 안됨
class PostArchiveView(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive.html'

class PostYearArchiveView(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_year.html'
    make_object_list = True

class PostMonthArchiveView(MonthArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_month.html'

class PostDayArchiveView(DayArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_day.html'

class PostTodayArchiveView(TodayArchiveView):
    model = Post
    date_field = 'modify_date'
    template_name = 'blog/archive/post_archive_day.html'



#taggit
class TagCloudTemplateView(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectListView(ListView):
    model = Post
    template_name = 'taggit/taggit_post_list.html'

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context



class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()

        context = dict()
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)



#CRUD
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'tags']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
        
    def get_success_url(self):
        return reverse('blog:detail',kwargs={'pk': self.object.id })

class PostChangeListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/post_change_list.html'    

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user).order_by('id')

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'description', 'content', 'image', 'tags']
    success_url = reverse_lazy('blog:index')

    def get_success_url(self):
        return reverse('blog:detail',kwargs={'pk': self.object.id })

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/archive/post_archive.html
{% extends 'base.html' %}
{% block title %}
post_archive.html       
{% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year {{ date|date:"Y" }}</a>
        </li>
    {% endfor %}
</ul>
<br>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/archive/post_archive_day.html
{% extends 'base.html' %}
{% block title %} 
post_archive_day.html       
{% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Post Archives for {{ month|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/archive/post_archive_month.html
{% extends 'base.html' %}
{% block title %}post_archive_month.html{% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
        <li><a href="{% url 'blog:post_day_archive' post.modify_date|date:'Y' post.modify_date|date:'b' post.modify_date|date:'j' %}">{{ post.modify_date|date:"Y-m-d" }}</a>&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

blog/templates/blog/archive/post_archive_year.html
{% extends 'base.html' %}
{% block title %}    post_archive_year.html    {% endblock %}
{% block add %}
<a class="nav-link" href="{% url 'blog:add' %}">Add</a>
{% endblock %}
{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:'Y'}} {{ date|date:"F" }}</a>
        </li>
    {% endfor %}
</ul>

<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}